.\"
.\" This file is part of rjk-nntp-tools.
.\" Copyright (C) 2015 Richard Kettlewell
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
.\" USA
.\"
.TH news-sources 1
.SH NAME
news-sources \- visualize news sources by peer
.SH SYNOPSIS
.B news-sources
.RI [ OPTIONS ]
.RB [ -- ]
.RI [ INPUT ...]
.SH DESCRIPTION
This program reads INN's news log file and generates daily graphs
showing the contributon of each peer.
The graphs are generated as PNG or SVG files, with HTML files to
display them.
All files are named for the date they correspond to.
.SH OPTIONS
.TP
.B -s\fR, \fB--state \fIPATH
Specify the state directory.
The default is the current directory.
.TP
.B -o\fR, \fB--output \fIPATH
Specify the output directory.
The default is the current directory.
.TP
.B -i\fR, \fB--index \fIPATH
Specify the index filename.
The name will be linked to the most recent HTML output.
Use an empty string to suppress this behavior.
The default is \fBindex.html\fR.
.TP
.B -T\fR, \fB--type \fITYPE
Specify the image type.
The possible choices are \fBpng\fR and \fBsvg\fR.
The default is \fBpng\fR.
.TP
.B -h\fR, \fB--help
Display a usage message.
.TP
.B -V\fR, \fB--version
Display version number.
.SH NOTES
In order to avoid double-counting, input can only go forward in time;
if it goes backwards, it will be ignored.
So it's important to order input files correctly.
.PP
INN's article log doesn't include years, so some guesswork is involved
at the start of a new year.
It also uses local time, so the output will reflect that, and there
are likely to be anomalies (e.g. undercounting) around DST shifts.
.PP
You may want to set up a cron job to clear out old state and output
files.
.SH EXAMPLE
.EX
news-sources /var/log/news/OLD/news.1.gz /var/log/news/news
.EE
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
.PP
http://www.greenend.org.uk/rjk/nntptools.html
