.\"
.\" This file is part of rjk-nntp-tools.
.\" Copyright (C) 2015 Richard Kettlewell
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
.\" USA
.\"
.TH news-sources 1
.SH NAME
news-sources \- visualize news sources by peer
.SH SYNOPSIS
.B news-sources
.RI [ OPTIONS ]
.SH DESCRIPTION
TODO
.SH OPTIONS
.TP
.B -i\fR, \fB--input \fIPATH
Specify the input filename.
The default is stdin.
.TP
.B -s\fR, \fB--state \fIPATH
Specify the state directory.
The default is the current directory.
.TP
.B -h\fR, \fB--help
Display a usage message.
.TP
.B -V\fR, \fB--version
Display version number.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
.PP
http://www.greenend.org.uk/rjk/2006/newstools.html
