char css[] = 
"body {\n"
"    color: black;\n"
"    background-color: white\n"
"}\n"
"\n"
"h1 {\n"
"    font-family: helvetica, arial, sans-serif;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"    padding: 0.2em;\n"
"    display: block\n"
"}\n"
"\n"
"h2,h3,h4,h5,h6 {\n"
"    font-family: helvetica, arial, sans-serif\n"
"}\n"
"\n"
"table {\n"
"    border-collapse: collapse\n"
"}\n"
"\n"
"td, th {\n"
"    border: 1px solid #404040;\n"
"    font-size: 12pt\n"
"}\n"
"\n"
"th {\n"
"    background-color: black;\n"
"    color: white\n"
"}\n"
;
