char css[] = 
"/*\n"
" * This file is part of spoolstats.\n"
" * Copyright (C) 2010 Richard Kettlewell\n"
" *\n"
" * This program is free software; you can redistribute it and/or modify\n"
" * it under the terms of the GNU General Public License as published by\n"
" * the Free Software Foundation; either version 2 of the License, or\n"
" * (at your option) any later version.\n"
" *\n"
" * This program is distributed in the hope that it will be useful, but\n"
" * WITHOUT ANY WARRANTY; without even the implied warranty of\n"
" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU\n"
" * General Public License for more details.\n"
" *\n"
" * You should have received a copy of the GNU General Public License\n"
" * along with this program; if not, write to the Free Software\n"
" * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307\n"
" * USA\n"
" */\n"
"body {\n"
"    color: black;\n"
"    background-color: white\n"
"}\n"
"\n"
"h1 {\n"
"    font-family: helvetica, arial, sans-serif;\n"
"    text-align: center;\n"
"    background-color: #f0f0f0;\n"
"    padding: 0.2em;\n"
"    display: block\n"
"}\n"
"\n"
"h2,h3,h4,h5,h6 {\n"
"    font-family: helvetica, arial, sans-serif\n"
"}\n"
"\n"
"a {\n"
"    text-decoration: none\n"
"}\n"
"\n"
"td A:link {\n"
"    color: black\n"
"}\n"
"\n"
"td A:visited {\n"
"    color: black\n"
"}\n"
"\n"
"td A:active {\n"
"    color: red\n"
"}\n"
"\n"
"table {\n"
"    border-collapse: collapse\n"
"}\n"
"\n"
"td, th {\n"
"    border: 1px solid #404040;\n"
"    font-size: 12pt\n"
"}\n"
"\n"
"th {\n"
"    background-color: black;\n"
"    color: white\n"
"}\n"
"\n"
"p.credits {\n"
"    font-size: 8pt;\n"
"    text-align: right\n"
"}\n"
"\n"
"p.graph {\n"
"}\n"
"\n"
"p.graph img {\n"
"    border: 1px solid black\n"
"}\n"
;
