.\"
.\" This file is part of rjk-nntp-tools.
.\" Copyright (C) 2010-11 Richard Kettlewell
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
.\" USA
.\"
.TH spoolstats 1
.SH NAME
spoolstats \- statistics on a news spool
.SH SYNOPSIS
.B spoolstats
.RI [ OPTIONS ]
.SH DESCRIPTION
Generates a report on posting volumes etc on a new spool.
.SH OPTIONS
.TP
.B -S \fIPATH\fR, \fB--spool \fIPATH
Sets the path to the news spool.
The default is
.IR /var/spool/news/articles .
.TP
.B -L \fIS\fB,\fIE\fR, \fB--latency \fIS\fB,\fIE
Set the spool latencies.
These define the relationships allowed between the date header in an
article and the time it arrives.
.IP
.I S
is the number of seconds "early" an article may arrive and still
be properly counted.
The default is 60s.
.IP
.I E
is the number of seconds "late" an article may arrive.
It defines the maximum propagation delay.
The default is 86400s (one day).
.TP
.B -N \fIDAYS\fR, \fB--days \fIDAYS
The number of days into the past to look.
The default is 7 days.
.TP
.B -H \fILIST\fR, \fB--hierarchies \fILIST
A comma-separate list of hierarchies to analyse.
May be specified more than once.
.TP
.B -8\fR, \fB--big8
Equivalent to a
.B --hierachies
option that lists the Big 8.
.TP
.B -Q\fR, \fB--quiet
Quieter operation.
.TP
.B --no-scan
Suppresses the scan phase.
Re-uses the results of the previous scan from the output directory.
.TP
.B --no-graph
Suppresses the reporting phase.
.TP
.B -h\fR, \fB--help
Display a usage message.
.TP
.B -V\fR, \fB--version
Display version number.
.SH "SAMPLING INTERVAL"
The sampling interval is defined by the
.B --days
and
.B --latency
options and the time the program is invoked.
The interval ends
.I E
seconds before the current time
and starts
.I DAYS
days before that.
So with the defaults, articles from the 7 days ending exactly 24 hours
ago will be considered.
.PP
The
.I S
parameter defines how much reliance is put on the timestamp of the
file (as an optimization).
With the default, an article can arrive up to 60 seconds "early" and
still be counted if its Date: header is within the sampling interval.
.SH OUTPUT
The output is a collection of linked HTML files.
.PP
.B index.html
contains a graph of historical traffic levels and a table giving
summary information about each hierarchy.
The hierarchy names can be clicked.
.PP
.B allgroups.html
contains a table giving summary information about every newsgroup.
.PP
For each hierarchy,
.IB HIERARCHY .html
gives the same information about just the newsgroups in that hierarchy.
.PP
.B agents.html
and
.B agents-summary.html
give the frequency of the different user agent strings.
The latter discards version and platform information to just give the
name of the client (as far as possible; there is no consistent
formatting, so a table of known clients is used).
.PP
In all cases, if Javascript is supported, the tables can be re-ordered
by clicking the headings.
.SH LOGS
.SS Formatting
Logfiles use a comma-separated value format.
In this version of CSV:
.IP \(bu
Integers are represented in decimal, and anything starting with a
digit is always an integer.
.IP \(bu
Strings are always introduced and terminated by \fB"\fR.
.IP \(bu
Strings use \fB\e\e\fR and \fB\e"\fR to represent \fB\e\fR and \fB"\fR.
.IP \(bu
Strings use \e\fIDDD\fR to represent any character in octal.
This representation never uses more than three digits.
.IP \(bu
Apart from the above, \fB\e\fR never appears in strings.
.PP
In the descriptions below, all fields are integers unless explicitly
marked as being strings.
.SS "Overall Logs"
.B all.csv
summarizes all articles scanned.
Each line has the following fields:
.TP
.B time
The time_t at the end of the sampling interval.
.TP
.B days
The length of the sampling interval in seconds.
.TP
.B bytes
The number of bytes in the all sampled articles.
.TP
.B articles
The number of sampled articles.
.PP
.I encodings.csv
records the encodings seen in the most recent scan phase.
Each line has the following fields:
.TP
.B encoding \fR(string)
The name of the encoding.
.TP
.B articles
The number of articles using this encoding.
.TP
.B senders
The number of unique senders using this encoding.
.PP
.I useragents.csv
records the user agents seen in the most recent scan phase.
Each line has the following fields:
.TP
.B agent \fR(string)
The full user agent string.
.TP
.B articles
The number of articles using this encoding.
.TP
.B senders
The number of unique senders using this encoding.
.SS "Hierarchy Logs"
Each hierarchy has a
.IB HIERARCHY .csv
summarizing articles scanned in that hierarchy.
Each line has the following fields:
.TP
.B time
The time_t at the end of the sampling interval.
.TP
.B days
The length of the sampling interval in seconds.
.TP
.B bytes
The number of bytes in the sampled articles.
.TP
.B articles
The number of sampled articles.
.TP
.B senders
The number of unique senders.
.PP
.IB HIERARCHY -groups.csv
contains per-group data from the most recent scan phase.
Each line has the following fields:
.TP
.B name \fR(string)
The name of the group.
.TP
.B bytes
The number of bytes in the sampled articles.
.TP
.B articles
The number of sampled articles.
.TP
.B senders
The number of unique senders.
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
.PP
https://www.greenend.org.uk/rjk/2006/newstools.html
