#! /usr/bin/perl -w
#
# Copyright (C) 2011 Richard Kettlewell
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
use strict;

sub quote {
    local $_ = shift;
    # Simple strings require no quoting at all
    if(/^[\-a-zA-Z0-9_:\/\.]+$/) {
        return $_;
    }
    # For preference use single quotes
    if(!/\''/) {
        return "'$_'";
    }
    # Otherwise escape funnies and use double quotes
    s/[\"\\]/\\$&/g;
    return "\"$_\"";
}

my %sites = (
    "lj" => "livejournal.com",
    "dw" => "dreamwidth.org"
    );

print "Welcome to setup-lj2news.  I will ask you some questions and then\n";
print "create a cron job to automatically gateway your journal into a\n";
print "newsgroup.\n";
print "\n";
print "Each question has a suggested answer in [square brackets].  You\n";
print "can accept this answer just by pressing ENTER.  Otherwise, enter\n";
print "the right answer and press ENTER.\n";
print "\n";
print "At any time you can press CTRL-C to quit.\n";
print "\n";
print "Press ENTER when you're ready to go.\n";

$_ = <STDIN>;

print "\n";
print "I need to know what site you use.\n";
for my $shortsite (sort keys %sites) {
    my $site = $sites{$shortsite};
    print "For $site, enter: $shortsite\n";
}
print "\n";
my $shortsite;
do {
    print "[lj] > ";
    chomp($shortsite = <STDIN>);
    $shortsite = 'lj' if $shortsite eq '';
} while(!exists $sites{$shortsite});
my $site = $sites{$shortsite};

print "\n";
print "I need to know your $site username.\n";
print "\n";
my $user;
my $rc;
do {
    print "[$ENV{LOGNAME}] > ";
    chomp($user = <STDIN>);
    $user = $ENV{LOGNAME} if $user eq '';
    $rc = system("wget -qO - http://$user.$site > /dev/null 2>&1");
    if($rc != 0) {
        print "\n";
        print "Oh dear; http://$user.$site does not seem to work.\n";
        print "If you are you sure '$user' is right, then perhaps $site\n";
        print "is down at the moment.  In that case, hit CTRL-C now\n";
        print "and try again later.\n";
        print "\n";
    }
} while($rc != 0);

my $domain;
if(-e "/etc/mailname") {
    open(MAILNAME, "</etc/mailname") or die "/etc/mailname: $!\n";
    chomp($domain = <MAILNAME>);
    close MAILNAME;
} else {
    $domain = `hostname -f`;
}

print "\n";
print "I need to know your email address.  I will use this in two ways:\n";
print "1) It will be the From: line of the news postings of your journal.\n";
print "2) It will be supplied to $site (per the LJ bot policy).\n";
print "\n";
my $email;
my $defaultEmail = "$ENV{LOGNAME}\@$domain";
do {
    print "[$defaultEmail] > ";
    chomp($email = <STDIN>);
    if($email eq '') {
        $email = $defaultEmail;
    }
    if($email !~ /\@/) {
        print "\n";
        print "Oh dear; that doesn't look like a valid email address to me.\n";
        print "\n";
    }
} while($email !~ /\@/);

print "\n";
print "I need to know your name.  I will put this in the From: line of the\n";
print "news postings of your journal.\n";
print "\n";
my $name;
my @pw = getpwnam($ENV{LOGNAME});
my $defaultName = $pw[6];
$defaultName =~ s/,.*//;
print "[$defaultName] > ";
chomp($name = <STDIN>);
if($name eq '') {
    $name = $defaultName;
}

print "\n";
print "I need to know what news server you want to use.\n";
print "\n";
my $newsServer;
my $defaultServer = $ENV{NNTPSERVER} || 'news';
do {
    print "[$defaultServer] > ";
    chomp($newsServer = <STDIN>);
    if($newsServer eq '') {
        $newsServer = $defaultServer;
    }
    $rc = system("host \Q$newsServer\E >/dev/null 2>&1");
    if($rc) {
        print "\n";
        print "Oh dear; that hostname doesn't seem to exist.\n";
        print "\n";
    }
} while($rc);

print "\n";
print "I need to know what newsgroup you want to post your journal to.\n";
print "\n";
my $newsgroup;
# TODO there should be a system-wide default.
do {
    print "[] > ";
    chomp($newsgroup = <STDIN>);
} while($newsgroup eq '');

my $userAgent = "http://www.greenend.org.uk/rjk/2006/newstools.html;$email";
my $url = "http://www.$site/users/$user/rss";

my @command = ("lj2news",
               "-a", $userAgent,
               "-t", $user,
               "-f", "$name <$email>",
               "-n", $newsgroup,
               "-s", $newsServer,
               $url);

my $command = join(" ", map(quote($_), @command));

print "\n";
print "OK, here is the command you will need:\n";
print "\n";
print "$command\n";
print "\n";

exit(0);

print "I can add this command to your crontab, to check your journal\n";
print "for fresh postings every hour.\n";
print "\n";
my $updateCron;
do {
    print "Modify your crontab?\n";
    print "[no] > ";
    chomp($updateCron = <STDIN>);
    if($updateCron ne 'yes' && $updateCron ne 'no') {
        print "\n";
        print "Sorry, I didn't understand that.  Please answer 'yes' or 'no'.\n";
        print "\n";
    }
} while($updateCron ne 'yes' && $updateCron ne 'no');

if($updateCron eq 'no') {
    print "\n";
    print "OK, I've not touched a thing.\n";
    exit(0);
}

# TODO
